### ISSUE TITLE
[Feature Request] Login and Sign Up page

### ISSUE THREAD

**Issue by supriyasinhaa** [LetsUpgrade/ONLINE-JOB-PORTAL#10]
# Login and Sign Up page
This is for the Job seeker module.

### Features to be Added
- Header and Footer should be same as the landing page.
- Separate page for login and Signup.
- Add normal sign in(Email and Password) and social sign in (Google, Linkedin)

**Comment by Tejas1510** [comment]
I would like to work on it

**Comment by keshav304** [comment]
can you assign me this issue?

**Comment by palakgupta2712** [comment]
I want to work on this task .

**Comment by avishkar2001** [comment]
Can you assign me this issue

**Comment by diyadheer** [comment]
I want to work on this issue
