### ISSUE TITLE
[Feature Request] List of Jobs applied Page

### ISSUE THREAD

**Issue by saibighnesh** [LetsUpgrade/ONLINE-JOB-PORTAL#11]
# List of Jobs applied Page

### Features to be Added
- Header and footer should be same for all the Job Seeker modules.
- Display the details in a tabular form (Job Title, Job Type, Salary, Applied On, Application Status)
- If the user has not applied anywhere, display appropriate message. For example : You have not applied for any job(s).

**Comment by RohitVarma001** [comment]
I would like to work on this issue?

**Comment by RohitVarma001** [comment]
I would like to work on this issue?

**Comment by Arsh4601** [comment]
I would like to work on this
