### ISSUE TITLE
[Feature Request] Logout Message Page

### ISSUE THREAD

**Issue by saibighnesh** [LetsUpgrade/ONLINE-JOB-PORTAL#13]
# Logout Message Page

### Features to be Added
- Header and footer will be same as the *Landing Page*
- Display a message like, "*You have been logged out successfully. See you soon.*"

**Comment by HariSuriya520** [comment]
I would like to work on this issue

**Comment by SoundharyaDGRT** [comment]
I would like to work on this issue

**Comment by diyadheer** [comment]
I would like to work on this issue.
