### ISSUE TITLE
[Feature Request] Landing Page for Job Seeker

### ISSUE THREAD

**Issue by snic82** [LetsUpgrade/ONLINE-JOB-PORTAL#14]
# Landing Page for Job Seeker

### Features to be Added
- Header and Footer should be same as the Job seeker module.
- Search option for posts and place.
- Display job vacancies by region and category.

**Comment by VigneshG1616** [comment]
I can code the HTML and CSS for this (either Pure HTML and CSS or Bootstrap both the ways I can contribute).

**Comment by keshav304** [comment]
I can work on this

**Comment by arnoob16** [comment]
I can code on this with HTML, CSS, JS, Bootstrap & JQuery
