### ISSUE TITLE
[Feature Request] My Saved Jobs Page

### ISSUE THREAD

**Issue by snic82** [LetsUpgrade/ONLINE-JOB-PORTAL#15]
# [*Job Seeker*] My Saved Jobs

### Features to be Added
- Header and Footer should be same as the Job seeker module.
- Display the details in a tabular form (*Job title, Job Type, Experience, Salary*)
- If the user has not saved any job, display appropriate message: *You have not saved any job*.

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by arnoob16** [comment]
I can work on the front-end of this project.

**Comment by RohitVarma001** [comment]
I want work on it
