### ISSUE TITLE
[Feature Request] My Account Page

### ISSUE THREAD

**Issue by snic82** [LetsUpgrade/ONLINE-JOB-PORTAL#16]
# [*Job Seeker*] My Account Page

### Features to be Added
- Header and Footer should be same as the Job seeker module.
- Create a typical my account page where we have features like:
  - Change Profile picture
  - Change Password
  - Remove account:
    - Delete
    - Deactivate

**Comment by shivang-prabhu** [comment]
I am interested in this

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by snehalkulabkar** [comment]
I'm interested in this

**Comment by lateef0407-zz** [comment]
I would like to do this
