### ISSUE TITLE
[Feature Request] [Recruiter] Sign Up Page

### ISSUE THREAD

**Issue by snic82** [LetsUpgrade/ONLINE-JOB-PORTAL#38]
# [Recruiter] Sign Up Page

### Features to be Added
Header and footer should be the same as the other pages
There will be form with the following fields:
- Company Name
- Location
- Official mail id
- Mobile/Landline
- Contact Person’s name
- Company Type
- Total Number of Employees
- A checkbox with the message : “I agree to Terms & Conditions and Privacy Policy”
- At the end there will be a “Create Account” Button

**Comment by debanshu08** [comment]
Kindly assign me this issue.

**Comment by keshav304** [comment]
I can work on this

**Comment by arnoob16** [comment]
I would like to work on this issue.

**Comment by Tejas1510** [comment]
Mam i would like to work on the issue

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by lateef0407-zz** [comment]
I can work on this
