### ISSUE TITLE
[Feature Request] [Recruiter] Dashboard

### ISSUE THREAD

**Issue by snic82** [LetsUpgrade/ONLINE-JOB-PORTAL#39]
# [Recruiter] Dashboard

### Features to be Added
- Header and Footer has to be responsive 
- There should be a sidebar with the same options like the dashboard
- The sidebar should be collapsible
- Have card/flash cards which will have tiles with headings like:
  - My Account
  - Post A Job
  - Job Post Status
  - Search Resumes
  - Messages
  - My Company

**Comment by RohitVarma001** [comment]
i am interested

**Comment by keshav304** [comment]
I can work on this
