### ISSUE TITLE
[Feature Request] [Recruiter] Candidates List

### ISSUE THREAD

**Issue by saibighnesh** [LetsUpgrade/ONLINE-JOB-PORTAL#43]
[Recruiter] Candidates List

### Features to be Added

- Header and footer
- A search bar to search the candidates 
- A dropdown filter for each job posted as well the status of the job
- After the filter is applied the candidate details should be visible as a card format

**Comment by keshav304** [comment]
I can work on this

**Comment by Arsh4601** [comment]
I can work  on this
