### ISSUE TITLE
[Feature Request] [Recruiter] Messages Page

### ISSUE THREAD

**Issue by saibighnesh** [LetsUpgrade/ONLINE-JOB-PORTAL#44]
[Recruiter] Messages Page

### Features to be Added

- Header and footer should be there
- In the left, the company details will be there in a card format.
- In the right hand side, the recruiter’s message for the task/interview (whatever it may be) 
- If there are no messages sent, display a message like, “No messages found.”

**Comment by SoundharyaDGRT** [comment]
I would like to work on this issue

**Comment by Arsh4601** [comment]
I cam work on this
