### ISSUE TITLE
[Feature Request] Landing /Home Page

### ISSUE THREAD

**Issue by KamalDGRT** [LetsUpgrade/ONLINE-JOB-PORTAL#5]
# Landing / Home Page

### Features to be Added
- Create landing page with header, footer and content

**Comment by palakgupta2712** [comment]
Can you assign this to me?

**Comment by palakgupta2712** [comment]
Can you please assign the task to me?

**Comment by HariSuriya520** [comment]
I would like to work on this issue

**Comment by avishkar2001** [comment]
I am Interested

**Comment by keshav304** [comment]
I can work on this
