### ISSUE TITLE
[Feature Request] About Us Page

### ISSUE THREAD

**Issue by supriyasinhaa** [LetsUpgrade/ONLINE-JOB-PORTAL#6]
# About Us Page

### Features to be Added
-  Create about us page
-  Header and footer should be same as the landing page.

**Comment by VigneshG1616** [comment]
I would like to create this page.

**Comment by debanshu08** [comment]
I would like to work on this issue

**Comment by avishkar2001** [comment]
I am Interested

**Comment by SoundharyaDGRT** [comment]
I would like to work on this isssue!

**Comment by RohitVarma001** [comment]
I would like to work on this issue?

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by prak20** [comment]
Interested
