### ISSUE TITLE
[Feature Request] [Jobseeker] My account Page

### ISSUE THREAD

**Issue by supriyasinhaa** [LetsUpgrade/ONLINE-JOB-PORTAL#63]
# [Jobseeker] My Account Page

### Features to be Added
- Header and Footer should be same as Jobseeker Module.
- Change Profile Section :
    - _Profile Name_ , _Location_ 
- Change Password Section :
    - _Current Password_ , _New Password_ , _Repeat Password_ , _Change Password Button_ , _Cancel changes Button_

**Comment by lateef0407-zz** [comment]
I want to do this!
