### ISSUE TITLE
[Feature Request] Contact Us Page

### ISSUE THREAD

**Issue by KamalDGRT** [LetsUpgrade/ONLINE-JOB-PORTAL#7]
# Contact Us Page

### Features to be Added
- Header and footer should be same as the landing page.
- Add a map section in the top
- A typical contact information page : [ Name, Email Address, Subject, Message, Send Message ]

**Comment by palakgupta2712** [comment]
Can you assign this to me?

**Comment by debanshu08** [comment]
Can I work on this issue?

**Comment by avishkar2001** [comment]
I am interested

**Comment by SoundharyaDGRT** [comment]
I would like to work on this issue

**Comment by RohitVarma001** [comment]
I would like to work on this issue?

**Comment by prak20** [comment]
I am interested

**Comment by prak20** [comment]
Interested

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by lateef0407-zz** [comment]
i would like to do this work

**Comment by RohitVarma001** [comment]
i would like to do this work

**Comment by palakgupta2712** [comment]
I'm interested.
