### ISSUE TITLE
[Feature Request] Post Resume Page

### ISSUE THREAD

**Issue by supriyasinhaa** [LetsUpgrade/ONLINE-JOB-PORTAL#8]
# Post Resume Page
This is for Job Seeker Module.

### Features to be Added
- Header and footer should be same as Landing Page.
- Add a section to upload resume or build resume.

**Comment by shivang-prabhu** [comment]
I am interested in this issue

**Comment by snehalkulabkar** [comment]
I would like to work on this

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by Arsh4601** [comment]
I would like to work on this

**Comment by lateef0407-zz** [comment]
I would like to do this
