### ISSUE TITLE
[Feature Request] Job Listing Page

### ISSUE THREAD

**Issue by KamalDGRT** [LetsUpgrade/ONLINE-JOB-PORTAL#9]
# Job Listing Page

This is for Job Seeker Module.

### Features to be Added
- Header and footer should have [Find Jobs, Create Resume, Create alert]
- Notification icon and User profile/name on the right of navbar. 
- User Profile/name should have a dropdown [ *My Resume, My Applied Jobs, My Saved Jobs, My Searches, My Jobs Alert, My Account, Log out* ]
- A search option with various filters such as _Job Name_, _Location_, *Company*, *Work Experience*, *Job Type*, *Salary*
- Display the jobs present
- Show the  job description in the same page either as a pop up or as a column
- Apply Now option should be present for the jobs
- Wishlist/Save for later option. [*This is for authenticated users*]

**Comment by shivang-prabhu** [comment]
I am interested in this

**Comment by snehalkulabkar** [comment]
I am interested in this issue

**Comment by Arsh4601** [comment]
I am interested

**Comment by lateef0407-zz** [comment]
i would like to do this work

**Comment by palakgupta2712** [comment]
I'm interested.

**Comment by keshav304** [comment]
I can work on this issue
